<?php
/**
 * Страница "Содержание".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью виджета веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Module "Visual editor"</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>Usable for: changes to template fragments, markup of application components on site pages, quick access to sections and articles of the site.</p>

    <h2>Contents:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('panel') ?>">Visual editor toolbar</a></li>
        <li><a href="<?= $url('markupblock') ?>">Template block markup</a></li>
    </ul>
</article>