<?php
/**
 * Страница "Панель инструментов Визуального редактора".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Visual editor panel tools</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/panel.png' ?>" />
    </div>
    <p>The default panel is positioned vertically on the screen along the left edge of the Visual editor.</p>
    <h2>Panel tools</h2>
    <ul class="g-help-list">
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-lighton.svg' ?>" /> <b>Enable page markup.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-refresh.svg' ?>" /> <b>Page refresh.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-back.svg' ?>" />  <img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-forward.svg' ?>" /> <b>Jump between pages.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-article.svg' ?>" /> <b>Editing an article.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-acategory.svg' ?>" /> <b>Editing an article category (section).</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-seo.svg' ?>" /> <b>Search engine optimization.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-components.svg' ?>" /> <b>Components of the current page.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-blocks.svg' ?>" /> <b>Fragments of the current page.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-blank.svg' ?>" /> <b>Opening a page in a new browser tab.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-help.svg' ?>" /> <b>Help.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</li>
    </ul>
</article>